CREATE DATABASE QLSV;
GO

USE QLSV;
GO

CREATE TABLE SinhVien (
    MaSV VARCHAR(15) PRIMARY KEY,
    TenSV NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
);
GO
CREATE TABLE Lop (
    MaLop VARCHAR(15) PRIMARY KEY,
    TenLop NVARCHAR(50) NOT NULL,
);
GO
CREATE TABLE LopSV (
    MaLop VARCHAR(15),
    MaSV VARCHAR(13),
	ChucVu NVARCHAR(50),
    PRIMARY KEY (MaLop, MaSV),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);
GO
CREATE TABLE Khoa (
    MaKhoa VARCHAR(15) PRIMARY KEY,
    TenKhoa NVARCHAR(50) NOT NULL,
);
GO
CREATE TABLE MonHoc (
    MaMon VARCHAR(15) PRIMARY KEY,
    TenMon NVARCHAR(50) NOT NULL,
    STC INT NOT NULL
);
GO
CREATE TABLE BoMon (
    MaBM VARCHAR(15) PRIMARY KEY,
    TenBM NVARCHAR(50) NOT NULL,
    MaKhoa VARCHAR(15) NOT NULL,
	FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);
GO
CREATE TABLE GiaoVien (
    MaGV VARCHAR(15) PRIMARY KEY,
    TenGV NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
    MaBM VARCHAR(15) NOT NULL,
    FOREIGN KEY (MaBM) REFERENCES BoMon(MaBM)
);
GO
CREATE TABLE GVCN (
    MaGV VARCHAR(15),
    MaLop VARCHAR(15),
	HK INT NOT NULL,
	PRIMARY KEY (MaLop, MaGV, HK),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
	FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV)
);
GO
CREATE TABLE LopHP (
    MaLopHP VARCHAR(15) PRIMARY KEY,
    TenLopHP VARCHAR(15) NOT NULL,
    HK INT NOT NULL,
	MaMon VARCHAR(15) NOT NULL,
	MaGV VARCHAR(15) NOT NULL,
    FOREIGN KEY (MaMon) REFERENCES MonHoc(MaMon),
    FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV)
);
GO
CREATE TABLE DKMH (
    MaLopHP VARCHAR(15) PRIMARY KEY,
    MaSV VARCHAR(13) NOT NULL,
    DiemTP FLOAT,
	DiemThi FLOAT,
	PhanTramThi FLOAT,
    FOREIGN KEY (MaLopHP) REFERENCES LopHP(MaLopHP),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);
GO